### Add Songs to Database

### Song 1
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "1",
  "title": "Awkward Apocalyptic Pickup",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/Awkward%20Apocalyptic%20Pickup.mp3"
}

### Song 2
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "2",
  "title": "Ambush in Rattlesnake Gulch",
  "artist": "David Renda",
  "url": "https://freepd.com/music/Ambush%20in%20Rattlesnake%20Gulch.mp3"
}

### Song 3
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "3",
  "title": "Improv for Evil",
  "artist": "Brian Boyko.",
  "url": "https://freepd.com/music/Improv%20for%20Evil.mp3"
}

### Song 4
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "4",
  "title": "Ambient Classical Guitar",
  "artist": "Bryan Teoh",
  "url": "https://www.bensound.com/bensound-music/bensound-sunny.mp3"
}

### Song 5
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "5",
  "title": "Ancient Rite",
  "artist": "Kevin MacLeod",
  "url": "https://www.bensound.com/bensound-music/bensound-summer.mp3"
}

### Song 6
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "6",
  "title": "Ascending",
  "artist": "Bryan Teoh",
  "url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
}

### Song 7
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "7",
  "title": "Battle Ready",
  "artist": "Bryan Teoh",
  "url": "https://freepd.com/music/Battle%20Ready.mp3"
}

### Song 8
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "8",
  "title": "Think About It",
  "artist": "Bryan Teoh",
  "url": "https://freepd.com/music/Think%20About%20It.mp3"
}

### Song 9
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "9",
  "title": "Release the Hybrids",
  "artist": "Bryan Teoh",
  "url": "https://freepd.com/music/Release%20the%20Hybrids.mp3"
}

### Song 10
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "10",
  "title": "Honor Bound",
  "artist": "Bryan Teoh",
  "url": "https://freepd.com/music/Honor%20Bound.mp3"
}

### Song 11
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "11",
  "title": "The Ice Giants",
  "artist": "Bryan Teoh",
  "url": "https://freepd.com/music/The%20Ice%20Giants.mp3"
}

### Song 12
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "12",
  "title": "Desert Fox",
  "artist": "Bryan Teoh",
  "url": "https://freepd.com/music/Desert%20Fox.mp3"
}

### Song 13
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "13",
  "title": "Go On Without Me",
  "artist": "Bryan Teoh",
  "url": "https://freepd.com/music/Go%20On%20Without%20Me.mp3"
}

### Song 14
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "14",
  "title": "Epic Blockbuster 2",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/Epic%20Blockbuster%202.mp3"
}

### Song 15
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "15",
  "title": "3 am West End",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/3%20am%20West%20End.mp3"
}

### Song 16
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "16",
  "title": "Adventure",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/Adventure.mp3"
}

### Song 17
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "17",
  "title": "Alien Invasion",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/Alien%20Invasion.mp3"
}

### Song 18
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "18",
  "title": "A Waltz For Naseem",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/A%20Waltz%20For%20Naseem.mp3"
}

### Song 19
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "19",
  "title": "Action Strike",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/Action%20Strike.mp3"
}

### Song 20
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "20",
  "title": "A Good Bass for Gambling",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/A%20Good%20Bass%20for%20Gambling.mp3"
}

### Song 21
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "21",
  "title": "A Surprising Encounter",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/A%20Surprising%20Encounter.mp3"
}

### Song 22
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "22",
  "title": "A Very Brady Special",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/A%20Very%20Brady%20Special.mp3"
}

### Song 23
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "23",
  "title": "Abstract Anxiety",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/Abstract%20Anxiety.mp3"
}

### Song 24
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "24",
  "title": "Adding the Sun",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/Adding%20the%20Sun.mp3"
}

### Song 25
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "25",
  "title": "Modern Island Jam",
  "artist": "Kevin MacLeod",
  "url": "https://freepd.com/music/Modern%20Island%20Jam.mp3"
}

### Song 26
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "26",
  "title": "Palm and Soul",
  "artist": "Kevin MacLeod",
  "url": "https://freepd.com/music/Palm%20and%20Soul.mp3"
}

### Song 27
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "27",
  "title": "Coy Koi",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/Coy%20Koi.mp3"
}

### Song 28
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "28",
  "title": "Bavarian Seascape",
  "artist": "Anonymous",
  "url": "https://freepd.com/music/Bavarian%20Seascape.mp3"
}

### Song 29
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "29",
  "title": "Aquatic City Vanished",
  "artist": "Bryan Teoh",
  "url": "https://freepd.com/music/Aquatic%20City%20Vanished.mp3"
}

### Song 30
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "id": "30",
  "title": "Forest Frolic Loop",
  "artist": "Kevin MacLeod",
  "url": "https://freepd.com/music/Forest%20Frolic%20Loop.mp3"
}

